In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
plt.style.use('ggplot') 
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

In [2]:
# read data
user_profile = pd.read_csv('./dataset/user_profile.csv')
first_session = pd.read_csv('./dataset/first_session.csv')

/Users/jacqueline/miniconda2/envs/py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
user_engagement = pd.read_csv('./dataset/user_engagement.csv')

In [10]:
user_profile.head()

,Unnamed: 0,user_id,user_signup_timestamp,state,zipcode,is_homeowner,gender,tradelines_avg_days_since_opened,tradelines_max_days_since_opened,tradelines_min_days_since_opened,...,total_mortgage_loans_balance,total_auto_loans_balance,total_student_loans_balance,count_inquiries_3_months,count_inquiries_6_months,count_inquiries_12_months,recent_bankruptcy_date,count_bankruptcy,age_bucket,credit_score_bucket
0,0,50991631a5e7fafd8b5856fc15e3d1a3af5dcf98,2018-07-25 21:06:12,AR,72762,True,Female,2385.16,7446.0,481.0,...,26049.0,0.0,0.0,0,0,0,NaN,0,"(45.0, 50.0]","(630.0, 635.0]"
1,1,18db173b8b0fb250985a4db2f3f8593ee9658707,2018-07-01 22:01:56,NE,68111,False,NaN,909.25,1780.0,152.0,...,0.0,12992.0,0.0,0,0,1,NaN,0,"(50.0, 55.0]","(575.0, 580.0]"
2,2,cabee62f0c4f26bb088f4a48d9ca5efa3a4f96e3,2018-07-02 08:47:21,AL,36078,False,Male,1544.00,3975.0,251.0,...,86987.0,0.0,0.0,0,0,1,NaN,0,"(50.0, 55.0]","(685.0, 690.0]"
3,3,bb34f48b56a57e834c5c612b835d5a691f7357e8,2018-07-02 02:07:53,MT,59923,True,Unisex,831.60,2573.0,40.0,...,148912.0,46046.0,0.0,3,3,12,NaN,0,"(50.0, 55.0]","(625.0, 630.0]"
4,4,6da929725c76c01aa151d97060df2e6bd051e31e,2018-07-03 17:36:42,PA,19040,False,Female,1226.60,2510.0,186.0,...,0.0,16262.0,24134.0,0,0,3,NaN,0,"(20.0, 25.0]","(630.0, 635.0]"

In [13]:
first_session[first_session['user_id']=='bb0fae985cd1a0a6613d8d32b6544026e11c8a56']

,Unnamed: 0,user_id,session_id,session_start_timestamp,user_signup_timestamp,action_timestamp,action_type,page_name,offer_lender,offer_product,offer_page_position,offer_card_id,browser_name,browser_version,app_version,login_platform,os_name
191193,196677,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:29:39,VIEW_OFFER,AOOP_OVERVIEW,3cc72f3330fc351b3436555f52573c94c18f5921,CREDIT_CARDS,NaN,da3d3fe7fc5c458506981b086d87cbb614b17772,Unknown,NaN,3.1.14,Mobile App,iOS
191253,196739,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:20:02,VIEW_OFFER,AOOP_OVERVIEW,3cc72f3330fc351b3436555f52573c94c18f5921,CREDIT_CARDS,NaN,da3d3fe7fc5c458506981b086d87cbb614b17772,Unknown,NaN,3.1.14,Mobile App,iOS
191283,196771,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:32:27,VIEW_OFFER,AOOP_OVERVIEW,3cc72f3330fc351b3436555f52573c94c18f5921,CREDIT_CARDS,NaN,da3d3fe7fc5c458506981b086d87cbb614b17772,Unknown,NaN,3.1.14,Mobile App,iOS
268456,276307,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:31:18,VIEW_OFFER,CC_DETAILS,3cc72f3330fc351b3436555f52573c94c18f5921,CREDIT_CARDS,BALANCE_TRANSFER,3c4431238075216ae3c34020c7982920374a94de,Unknown,NaN,3.1.14,Mobile App,iOS
348660,359137,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:39:44,VIEW_OFFER,AOOP_OVERVIEW,3cc72f3330fc351b3436555f52573c94c18f5921,CREDIT_CARDS,NaN,da3d3fe7fc5c458506981b086d87cbb614b17772,Unknown,NaN,3.1.14,Mobile App,iOS
348878,359365,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:20:09,VIEW_OFFER,AOOP_OVERVIEW,3cc72f3330fc351b3436555f52573c94c18f5921,CREDIT_CARDS,NaN,da3d3fe7fc5c458506981b086d87cbb614b17772,Unknown,NaN,3.1.14,Mobile App,iOS
430743,443515,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:40:00,VIEW_OFFER,AOOP_OVERVIEW,44767123b13b839733d3207eb6ddd13fd6c66a06,PERSONAL_LOANS,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
606973,623428,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:29:45,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
606981,623436,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:24:12,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
607788,624243,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:30:06,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
795483,813484,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:32:36,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
795490,813491,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:29:31,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
795585,813586,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:23:41,VIEW_PAGE,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
795593,813594,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:23:04,VIEW_PAGE,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
888325,907663,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:32:49,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
888326,907664,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:20:52,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
985436,1007627,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:29:55,VIEW_OFFER,AOOP_OVERVIEW,d3f02e63cbf0f2cd1389baa668338f80f7055a8e,CREDIT_CARDS,NaN,78d4b0767619678b942b32a9a88d327b97f6af0c,Unknown,NaN,3.1.14,Mobile App,iOS
985661,1007857,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:40:25,VIEW_OFFER,AOOP_OVERVIEW,d3f02e63cbf0f2cd1389baa668338f80f7055a8e,CREDIT_CARDS,NaN,78d4b0767619678b942b32a9a88d327b97f6af0c,Unknown,NaN,3.1.14,Mobile App,iOS
1072355,1098754,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:32:28,VIEW_OFFER,AOOP_OVERVIEW,17856bac3d2a6b5108ccca81bdfe8469e5e0fdb3,BANKING,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
1072652,1099058,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:39:45,VIEW_OFFER,AOOP_OVERVIEW,d3f02e63cbf0f2cd1389baa668338f80f7055a8e,CREDIT_CARDS,NaN,78d4b0767619678b942b32a9a88d327b97f6af0c,Unknown,NaN,3.1.14,Mobile App,iOS
1072697,1099104,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:40:00,CLICK,AOOP_OVERVIEW,44767123b13b839733d3207eb6ddd13fd6c66a06,PERSONAL_LOANS,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
1072739,1099147,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:39:45,VIEW_OFFER,AOOP_OVERVIEW,17856bac3d2a6b5108ccca81bdfe8469e5e0fdb3,BANKING,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
1254287,1292317,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:31:18,VIEW_OFFER,CC_DETAILS,d65eb6205af9b7f4e475e3f6fc087a34422883c6,CREDIT_CARDS,BALANCE_TRANSFER,b0921ddb1170697cfaca435428a1254b90ae8d05,Unknown,NaN,3.1.14,Mobile App,iOS
1254401,1292462,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:31:33,CLICK,CC_DETAILS,NaN,NaN,BALANCE_TRANSFER,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
1254430,1292492,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:31:11,VIEW_PAGE,CC_DETAILS,NaN,NaN,BALANCE_TRANSFER,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
1343625,1384704,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:29:59,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
1343685,1384764,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:32:42,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
1343700,1384779,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:24:14,VIEW_PAGE,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
1344029,1385109,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:21:21,CLICK,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
1344508,1385589,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:32:26,VIEW_PAGE,AOOP_OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7936795,8474593,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:30:44,CLICK,MY_DEBT,NaN,NaN,MY_DEBT:_CREDIT_CARDS,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7936951,8474749,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:41:16,CLICK,MY_DEBT,NaN,NaN,MY_DEBT:_CREDIT_CARDS,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7938110,8475957,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:30:52,CLICK,MY_DEBT,NaN,NaN,MY_DEBT:_CREDIT_CARDS,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7938152,8475999,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:32:02,CLICK,MY_DEBT,NaN,NaN,MY_DEBT:_CREDIT_CARDS,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7938210,8476059,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:20:52,VIEW_OFFER,MY_BORROWING_POWER,57813bdbaac0250fe67f69a0e928a661d2a94f41,MORTGAGES,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7938227,8476077,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:34:28,VIEW_OFFER,MY_BORROWING_POWER,d3f02e63cbf0f2cd1389baa668338f80f7055a8e,CREDIT_CARDS,NaN,78d4b0767619678b942b32a9a88d327b97f6af0c,Unknown,NaN,3.1.14,Mobile App,iOS
7938235,8476085,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:30:38,CLICK,MY_DEBT,NaN,NaN,MY_DEBT:_CREDIT_CARDS,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7938754,8476625,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:40:43,VIEW_OFFER,MY_DEBT,d3f02e63cbf0f2cd1389baa668338f80f7055a8e,CREDIT_CARDS,MY_DEBT:_CREDIT_CARD,bfac0bc45d43dbe486dcc347d037d55e46bcab1a,Unknown,NaN,3.1.14,Mobile App,iOS
7984808,8537372,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:39:36,CLICK,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7984809,8537373,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:39:26,VIEW_PAGE,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7984813,8537377,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:38:26,VIEW_PAGE,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7984832,8537396,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:22:34,CLICK,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7985133,8537699,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:33:00,VIEW_PAGE,MY_CREDIT,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7985341,8537907,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:33:14,VIEW_PAGE,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7985346,8537912,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:33:21,CLICK,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7985347,8537913,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:33:22,CLICK,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7985348,8537914,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:22:50,CLICK,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7985349,8537915,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:38:18,CLICK,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7985466,8538034,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:25:12,CLICK,MY_CREDIT,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7985608,8538177,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:24:40,CLICK,MY_CREDIT,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7985610,8538179,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:24:35,CLICK,MY_CREDIT,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7986698,8539269,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:20:13,CLICK,OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
7986728,8539299,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:11:57,CLICK,SIGNUP1_-_ACCOUNT_CREATION,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
8018582,8583583,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:22:38,CLICK,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
8018662,8583665,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:22:33,CLICK,MY_RECOMMENDATIONS,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
8018767,8583771,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:21:54,CLICK,MY_CREDIT,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
8019337,8584342,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:24:12,VIEW_PAGE,MY_CREDIT,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
8020414,8585422,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:24:15,CLICK,OVERVIEW,NaN,NaN,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS
8051941,8628595,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:21:25,VIEW_OFFER,CC_BEST_CARDS,b340725f5f85a98168a9969ed1a31e9b60f1d3a1,CREDIT_CARDS,BEST_CARDS,9aebc40bc2016a475f8a9f9e6d1103a5c6318248,Unknown,NaN,3.1.14,Mobile App,iOS
8053411,8630240,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,645c585bbde184f87516ef7f62269a06c5a0f72f,2018-07-01 06:12:06,2018-07-01 06:12:06,2018-07-01 06:21:21,VIEW_PAGE,CC_BEST_CARDS,NaN,CREDIT_CARDS,NaN,NaN,Unknown,NaN,3.1.14,Mobile App,iOS

In [14]:
user_engagement[user_engagement['user_id']=='bb0fae985cd1a0a6613d8d32b6544026e11c8a56']

,Unnamed: 0,session_id,user_id,session_length,view_count,view_aoop_overview_count,view_my_credit_count,view_credit_monitoring_count,view_my_recommendations_count,view_my_borrowing_power_count,...,click_count_auto_products.1,logged_in_count,session_start_timestamp,city,state,browser_name,browser_version,app_version,login_platform,os_name
19,19,645c585bbde184f87516ef7f62269a06c5a0f72f,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,1775,52,14,8,0,6,6,...,0,1,2018-07-01 06:12:06,Ferrum,VA,Unknown,NaN,3.1.14,Mobile App,iOS
43,43,2c239e26dc0a152577de293bbc57881d6e912450,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,106,4,1,1,0,1,1,...,0,1,2018-07-02 03:09:27,Ferrum,VA,Unknown,NaN,3.1.14,Mobile App,iOS
589,589,0b137c1df0b04009553238ad30e663043ebb19b5,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,50,4,2,0,0,0,1,...,0,1,2018-07-01 09:26:47,Roanoke,VA,Unknown,NaN,3.1.14,Mobile App,iOS
1365,1365,ea3a76c7b7b562301f7f1d19c8a6cc859b764e38,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,65,7,2,1,0,0,1,...,0,1,2018-07-06 08:31:22,Ferrum,VA,Unknown,NaN,3.1.14,Mobile App,iOS
1774,1774,7e2bdf67f715fc0d2cbe0f64a96865970e5f9856,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,48,4,2,1,0,0,1,...,0,1,2018-07-06 07:54:05,Ferrum,VA,Unknown,NaN,3.1.14,Mobile App,iOS
11551,11551,7a2457c91d6e91ab35c5e129acd71b7f0a0a6282,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,157,46,18,6,0,4,2,...,0,2,2018-07-24 20:31:00,Lynchburg,VA,Unknown,NaN,3.1.14,Mobile App,iOS

In [28]:
user_engagement.columns

Index(['Unnamed: 0', 'session_id', 'user_id', 'session_length', 'view_count',
       'view_aoop_overview_count', 'view_my_credit_count',
       'view_credit_monitoring_count', 'view_my_recommendations_count',
       'view_my_borrowing_power_count', 'view_cc_best_cards_count',
       'view_my_debt_count', 'view_cc_my_borrowing_power_count',
       'view_cc_approval_odds_count', 'view_cc_details_count',
       'view_my_credit_report_count', 'view_increase_total_credit_limit_count',
       'view_cc_marketplace_count', 'view_alert_count', 'click_count',
       'click_count_credit_card', 'click_count_personal_loan',
       'click_count_mortgage', 'click_count_credit_repair',
       'click_count_banking', 'click_count_auto_products', 'click_apply_count',
       'click_count_credit_card.1', 'click_count_personal_loan.1',
       'click_count_mortgage.1', 'click_count_credit_repair.1',
       'click_count_banking.1', 'click_count_auto_products.1',
       'logged_in_count', 'session_start_timestamp', 'city', 'state',
       'browser_name', 'browser_version', 'app_version', 'login_platform',
       'os_name'],
      dtype='object')

In [12]:
user_engagement[user_engagement['user_id'].duplicated()]

,Unnamed: 0,session_id,user_id,session_length,view_count,view_aoop_overview_count,view_my_credit_count,view_credit_monitoring_count,view_my_recommendations_count,view_my_borrowing_power_count,...,click_count_auto_products.1,logged_in_count,session_start_timestamp,city,state,browser_name,browser_version,app_version,login_platform,os_name
43,43,2c239e26dc0a152577de293bbc57881d6e912450,bb0fae985cd1a0a6613d8d32b6544026e11c8a56,106,4,1,1,0,1,1,...,0,1,2018-07-02 03:09:27,Ferrum,VA,Unknown,NaN,3.1.14,Mobile App,iOS
74,74,75dfb253bbef49ce4346f9abe0b0e007949a800d,d4ead697c49f13cc7d5576236e0499973776a223,25,2,0,0,0,0,0,...,0,1,2018-07-02 21:03:17,Passaic,NJ,Chrome Mobile,67.0,NaN,Mobile Web,Android
77,77,ca944b2cfaf26f8399ba33a08ff3cadfd84e28eb,f3728870beed9fc8a5cd84d1474aafd996841169,321,7,0,0,0,0,0,...,0,1,2018-07-01 18:42:34,Pittsburgh,PA,Unknown,NaN,3.1.15,Mobile App,Android
102,102,4ad760908da478d5bcc9321ee41340c9d71d7ec5,ecb5ce4fb21dc8c816d545090d70f03aa2b3299e,163,8,1,0,0,0,1,...,0,1,2018-07-02 07:47:15,Keauhou,HI,Chrome Mobile,67.0,NaN,Mobile Web,Android
104,104,5655cd4103dc02a13c21dcea803e6245286861c3,20cd139d2abb1079dbcaea386f37c1f905f73a41,24,2,1,0,0,0,0,...,0,1,2018-07-02 16:53:49,Rome,NY,Unknown,NaN,3.1.14,Mobile App,iOS
118,118,ff31c40ba251785db99763144ae812f695b31b8a,0a7cdcf644d89a3c998bc01f8fdaed769956ed0a,1208,14,1,1,0,1,0,...,0,0,2018-07-01 18:51:31,Memphis,TN,Chrome,67.0,NaN,Web,Windows
119,119,b03b616d7de613c2dff166ae26d53a02e80e5755,f3728870beed9fc8a5cd84d1474aafd996841169,118,4,0,0,0,0,0,...,0,1,2018-07-01 19:15:29,Pittsburgh,PA,Unknown,NaN,3.1.15,Mobile App,Android
121,121,00ccfd19d7e8f81766fd01a1dd78920cc576cf87,466df7aa1dca7cddd89c8d812b3e0f23e8782ed9,35,1,0,0,0,0,0,...,0,1,2018-07-01 21:46:33,Arnold,MD,Safari 9,9.1,NaN,Web,OS X
137,137,c07fc744073a048373435c41971d9d7888a1d454,46b940a7f85e2806eb74838738698c66d1fcf351,0,1,0,0,0,0,0,...,0,0,2018-07-02 08:07:52,Louisville,KY,Mobile Safari,11.0,NaN,Mobile Web,OS X
138,138,a5bc94bea894b71f4bb5ee0e177d396fc24528d3,910b222a77a3c59a16b9b88eade28d6279b10b3d,205,5,2,1,0,0,0,...,0,1,2018-07-02 11:54:07,Minneapolis,MN,Mobile Safari,11.0,NaN,Mobile Web,OS X
144,144,898927bacf73d62d16f1eeee66de4758effe8254,063620daa8cbb148be037e10a60a101c7025bf02,53,2,1,0,0,0,0,...,0,1,2018-07-02 20:18:41,Rochester,NY,Unknown,NaN,3.1.15,Mobile App,Android
148,148,31f58f7656101fb9d32700b4e23866c98acc9bf7,91475e4981be3ed3f3054286aba0c30a9ca92a46,702,7,1,1,0,1,0,...,0,1,2018-07-03 00:07:50,Bellevue,WA,Mobile Safari,11.0,NaN,Mobile Web,OS X
161,161,9b712c2914f9d9cefc5ffcb22352fe5851e7798e,3e675e92e0c8e6db5e94ddd616aaf502d8c688ee,1517,15,3,3,0,1,0,...,0,2,2018-07-02 02:51:32,Minneapolis,MN,Chrome Mobile,67.0,NaN,Mobile Web,Android
171,171,bf7020de12dd641077b8943b2f842c1504ec8a8d,91e259bffcb144973e6b91d96800c10a8290d25a,31,4,0,0,0,0,0,...,0,0,2018-07-01 11:34:07,NaN,NC,Chrome Mobile,67.0,NaN,Mobile Web,Android
176,176,3727930195fa5447e46a3c9f32c68ee7e88cab75,f3728870beed9fc8a5cd84d1474aafd996841169,66,5,2,0,0,0,0,...,0,1,2018-07-01 19:32:43,Pittsburgh,PA,Unknown,NaN,3.1.15,Mobile App,Android
182,182,a7ec75390fb5185ed0d851b3d9b6afe5e05d35b3,d4c80e7c06369d2b6397d082ef4f1eb7035aed7d,168,7,1,0,0,0,0,...,0,1,2018-07-02 12:11:18,Livonia,MI,Unknown,67.0,3.1.15,Mobile App,Android
192,192,af432c38ff01d2f9f530f802a3387978ca8970fd,8a802bd9d44c9c7633cfbe9686ce258d81dcecfe,1824,12,1,1,0,0,2,...,0,1,2018-07-01 18:15:22,Danville,VA,Mobile Safari,11.0,NaN,Mobile Web,OS X
193,193,30a1dfe9399c5b7dd32b5dcbc6962b8d950453c2,d041440af9e3d3b3af9fe03d5c92fa997962d287,398,6,2,0,0,0,0,...,0,1,2018-07-01 18:46:00,NaN,OK,Chrome Mobile,67.0,NaN,Mobile Web,Android
194,194,1364b8266fd479c128950020e285b44287629b15,9a2157f14ac90dff33632d0a28e9c97d8dcf56ab,13,5,2,0,0,0,0,...,0,1,2018-07-01 19:08:08,Chicago,IL,Unknown,NaN,3.1.15,Mobile App,Android
211,211,50b9b1699d39a958fac61e70b23badde22c19d63,4b1f72f3469872e57e7686987cd04708a1d4cc48,650,2,1,0,0,0,0,...,0,1,2018-07-01 20:28:06,Wilmington,DE,Chrome Mobile,51.0,NaN,Mobile Web,Android
212,212,da442daeedf62cd6c5527a26386c96ed5776bb8b,378bd0f1d9014410090e9a76c33998a2897dc59a,261,2,0,0,0,0,0,...,0,0,2018-07-02 06:07:42,Dracut,MA,Unknown,NaN,3.1.14,Mobile App,iOS
215,215,f8f9744cecc538f0affff8e8eb91232b6dd468a7,1ed6786a92fac1495c70d189aad026c166ec5d28,222,10,2,1,0,0,0,...,0,1,2018-07-02 15:48:34,Bartow,FL,Unknown,NaN,3.1.14,Mobile App,iOS
216,216,dc4e9d28197c0344a2290f18c8b1487a7422332a,787e4497248d7b3bae0653e607719fce2af06d56,538,4,1,1,0,0,0,...,0,1,2018-07-02 16:50:17,Millbrook,AL,Mobile Safari,NaN,NaN,Mobile Web,OS X
221,221,b758422e3945718f55df180e98d88a5c349d6d50,40a618131e135beacb0e1a6a0685611864a0cb5a,328,8,1,1,0,1,1,...,0,1,2018-07-03 11:50:36,Columbus,OH,Chrome,67.0,NaN,Web,Windows
227,227,97f15fd45e60aa930aedd0a9065f3c826abb639b,3c29af7ba09f31621e37529af5c8b96fe2f471c2,415,12,2,0,0,1,0,...,0,1,2018-07-03 18:18:49,NaN,TX,Unknown,NaN,3.1.15,Mobile App,Android
229,229,a512f8e0f83c1f267c70be8350da99f26c8f78c5,f3728870beed9fc8a5cd84d1474aafd996841169,73,7,3,0,0,1,1,...,0,1,2018-07-01 19:55:28,Pittsburgh,PA,Unknown,NaN,3.1.15,Mobile App,Android
232,232,fd296208d8518f249373067fa2e376285934e968,70b53604bf00f7b179b72911562b44d2355f2cf0,210,2,1,0,0,0,0,...,0,1,2018-07-02 00:53:20,Providence,RI,Mobile Safari,NaN,NaN,Mobile Web,OS X
238,238,34ec46ce70a925f4a47e5c9fec64185daa2c6ff5,a6ebfd72c3740d71159f3b2680c7d65c2ea3446a,329,2,1,0,0,0,0,...,0,1,2018-07-02 21:30:40,Torrance,CA,Chrome Mobile,67.0,NaN,Mobile Web,Android
244,244,099e8567c70317ea508e1b1d1e8788407a881899,ad604a5a1ce38ca9e5671344c16453f65dee831a,106,1,1,0,0,0,0,...,0,1,2018-07-03 10:40:54,Charlotte,NC,Unknown,NaN,3.1.15,Mobile App,Android
248,248,acb3d82a3cc2cc57f9e73854fecbfb4fc90c22d2,60513e969b461d15bc6f91a7a822177b9126c5f4,840,5,2,0,0,0,1,...,0,1,2018-07-01 10:19:32,Saint Cloud,MN,Mobile Safari,11.0,NaN,Mobile Web,OS X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176828,1176828,877d50f7bfbc4c0e08cc983f10bad60f0946bad6,97efd7c37f5f0dee2b3aeef01b22bbcd4bf83b50,99,4,1,0,0,0,0,...,0,1,2018-08-27 15:12:33,Vancouver,WA,Chrome Mobile,68.0,NaN,Mobile Web,Android
1176829,1176829,30f006b03b89a0e2db93d288d4579622d72a8435,d110c461dbb0b90c9cbf1d69d9ba14821ff939cd,182,5,0,0,0,0,0,...,0,0,2018-08-29 13:34:14,Chicago,IL,Mobile Safari,11.0,NaN,Mobile Web,OS X
1176830,1176830,de383646f642379e639600d4486ad93547799973,87b6a9fcbecd4843751c2cc508adb23fe3eebc98,2,1,0,0,0,0,0,...,0,0,2018-08-30 22:04:05,San Antonio,TX,Chrome Mobile,67.0,NaN,Mobile Web,Android
1176831,1176831,511df9b7c945a94a87b3a19df427df9c0cc38ce9,9a15205a7e31f623113c5e4b1ec0f3914323ffad,29,2,2,0,0,0,0,...,0,1,2018-08-29 20:51:42,NaN,PA,Unknown,NaN,3.1.16,Mobile App,Android
1176832,1176832,be73c5989192396aaa81255b63b907949d582e4e,0f4a484c4344264261b2565366b68d45784234ed,169,3,1,1,0,0,0,...,0,1,2018-08-27 20:04:03,Houston,TX,Unknown,NaN,3.1.15,Mobile App,iOS
1176833,1176833,3d4080710cdd3c6a98f7cacd76eb81d7b95d60b9,afcacc5a2da2c1d087d7b5a13f11d3e53516cffc,63,5,1,0,0,0,0,...,0,1,2018-08-28 05:13:47,Lima,OH,Chrome Mobile,68.0,NaN,Mobile Web,Android
1176834,1176834,5aa6b1de8de57fde07d5eb6c498f67c22be5393e,715c2b1a5333db07d366e0b0bbafbd30e53835ea,0,1,0,0,0,0,0,...,0,0,2018-08-24 17:41:50,Oakland,CA,Chrome Mobile,67.0,NaN,Mobile Web,OS X
1176835,1176835,2ab416b6d87baa2d69912b816aae299136dc403f,17f348e4ce744c1f034fe79ec7c52280cf618805,7,1,0,0,0,0,0,...,0,0,2018-08-27 23:36:36,Renton,WA,Mobile Safari,11.0,NaN,Mobile Web,OS X
1176836,1176836,e4393268b8f485706486e6933e5e952ddc987664,d8d7e9daa5659d31175b6872beeae9c4f61065bd,0,1,0,0,0,0,0,...,0,0,2018-08-22 20:51:54,Sacramento,CA,Mobile Safari,11.0,NaN,Mobile Web,OS X
1176837,1176837,650a7430b7ceb16c483e2c12d22bbf3d01e3c8e8,79349871bbdeb20868e2789d87fa2514e742e793,42,2,0,0,0,1,0,...,0,1,2018-08-22 21:28:41,Stamford,CT,Mobile Safari,11.0,NaN,Mobile Web,OS X
1176838,1176838,3f1249ec9e5a6efbabb31a1dc6068706157d24cf,f72f60d6d5efc0951eabc03275897743789b05b6,27,4,1,0,0,0,0,...,0,1,2018-08-28 10:01:02,Mobile,AL,Chrome Mobile,59.0,NaN,Mobile Web,Android
1176839,1176839,54eaf8e8a9ab0daf935bb37e7199db250ff29696,0d49009490f8a7bc52ee642a5694c29809f3f46b,54,2,0,0,1,0,0,...,0,1,2018-08-25 09:54:09,NaN,PA,Chrome Mobile,68.0,NaN,Mobile Web,Android
1176840,1176840,738c948dd4fde896ae2c18b3a39eca1f67daba99,73ae50c0c3f4bc6f1756eb082a1e11dffd2564ad,0,1,0,0,0,0,0,...,0,0,2018-08-23 05:17:36,Hayward,CA,Chrome Mobile,67.0,NaN,Mobile Web,Android
1176841,1176841,e6078ff8d7bd8648e2bf8cf30c155c44114924b3,7fd4b03763cf38aa6117ce0f90d1cd307979cee6,205,3,0,1,0,0,0,...,0,1,2018-08-23 13:37:28,Dover,NH,Chrome,68.0,NaN,Web,Windows
1176842,1176842,e6f042d0e05232d359e6eaf88e7ff0dda88d0d95,a6149bea180ca7837fd31c763b27af63504acabc,297,4,1,0,0,0,0,...,0,1,2018-08-25 21:12:55,Dallas,TX,Chrome Mobile,59.0,NaN,Mobile Web,Android
1176843,1176843,9d54433e76ac529e8cd300ea2a866dd809a0faf2,1e7085baa1891724a03548742f916a0f2d40a44d,1,1,0,0,0,0,0,...,0,0,2018-08-25 23:59:37,Los Angeles,CA,Mobile Safari,11.0,NaN,Mobile Web,OS X
1176844,1176844,4f03ec54e6d20f90465d6be5403fc85150f57c52,769f894c94885b23dde7306ae28966496b72bc2e,6,1,0,0,0,0,0,...,0,0,2018-08-24 01:16:19,NaN,AL,Chrome Mobile,67.0,NaN,Mobile Web,Android
1176845,1176845,23222b5b6f0137427b8b5969e1e0e576a163f8b3,ade28c95d117fd9063ed95a6f2290ef977e22c77,3,1,0,0,0,0,0,...,0,0,2018-08-24 02:57:19,West Covina,CA,Chrome Mobile,58.0,NaN,Mobile Web,Android
1176846,1176846,6335a5a6deec1b67299c72fe0fbff4871e384d66,629d7ebaadba5c4bb6e5a9e0d54e77ebf7c48266,0,1,0,0,0,0,0,...,0,0,2018-08-29 23:42:25,Hamburg,PA,Apple WebKit,NaN,NaN,Mobile Web,OS X
1176847,1176847,e8ac1291d226e693371785318c849d6efd1d32e2,1055421f239df992466f51e876a3e6bb852764cc,38,1,1,0,0,0,0,...,0,1,2018-08-30 01:25:55,Baton Rouge,LA,Unknown,NaN,3.1.15,Mobile App,iOS
1176848,1176848,e628c793b2a85d126ad340dcc5f915d2bbe6cbb0,84e9e8fb6e302cb52a84fbad07c169e4c3dfb09c,2,1,0,0,0,0,0,...,0,0,2018-08-25 17:40:37,Rancho Cucamonga,CA,Apple WebKit,NaN,NaN,Mobile Web,OS X
1176849,1176849,b0d4d20a2e7ce9519bc1635d528a5658f3362461,4a6b94fe633b01b6467a522f27b3c0964813b347,321,30,3,0,0,0,0,...,0,1,2018-08-25 17:48:42,Maryville,TN,Apple WebKit,NaN,3.1.15,Mobile App,iOS
1176850,1176850,12b0e3bc3ff4e186ef0393b89a0bc1cb39e56fb0,c02025991f89c5ec93bf4f6932653c926317300f,30,1,1,0,0,0,0,...,0,1,2018-08-28 12:56:37,Harvey,LA,Unknown,NaN,3.1.16,Mobile App,Android
1176851,1176851,01e4247c3cd17301d756ce3712d0ba630265a915,1cc9b11a14b53014e3e7f43c29008a530e51a2bd,5,1,0,0,0,0,0,...,0,1,2018-08-26 16:08:21,Braselton,GA,Chrome Mobile,67.0,NaN,Mobile Web,Android
1176852,1176852,f1a33b9ca161769128faa8050035cfcd1a17d790,6a79fd4794d472f783661949e8a5077727435c8a,1,1,0,0,0,0,0,...,0,0,2018-08-29 00:16:05,Central Islip,NY,Mobile Safari,11.0,NaN,Mobile Web,OS X
1176853,1176853,955792ea4f7a194a950c91e85fa69b5d63ecba0e,d493f9af5b7cd823c4cf0c1a57f8a10b01546efc,221,6,1,1,0,0,0,...,0,1,2018-08-27 18:54:33,Salisbury,MD,Mobile Safari,11.0,NaN,Mobile Web,OS X
1176854,1176854,266b5c55b861698dedd72e1b05ac72870ec23d3c,85c5f5397621eca809e42a3c24beff12f0049453,52,5,0,1,3,0,0,...,0,1,2018-08-30 13:37:35,Malden,MA,Chrome Mobile,59.0,NaN,Mobile Web,Android
1176855,1176855,6e1465da67d64abb6984bc39afbdb05b6185a77d,537eabae0d9e4c46d68e71a05944bef890caf025,240,4,0,0,0,0,0,...,0,0,2018-08-30 23:55:15,San Bernardino,CA,Mobile Safari,11.0,NaN,Mobile Web,OS X
1176856,1176856,6821ce9ab980363998fb64a3824a3009aa6edc0d,d74578366995540fb3f470ba0f4e34bfd3422340,1,1,0,0,0,0,0,...,0,0,2018-08-29 02:55:14,Melrose Park,IL,Chrome Mobile,68.0,NaN,Mobile Web,Android
1176857,1176857,a9e0c222a90e4394ce6daa3b9e2edde5124ca747,9402527812d4d8f2de777c86854717d56c78b280,540,4,2,1,0,0,1,...,0,1,2018-08-29 18:14:18,Portland,OR,Unknown,NaN,3.1.15,Mobile App,iOS

In [26]:
user_session = first_session.groupby(['user_id','session_id'], as_index=False)['session_start_timestamp','action_timestamp'].max()

In [27]:
user_session.head()

,user_id,session_id,session_start_timestamp,action_timestamp
0,0000485dbdc19e76bedcaf155b4de9491f414a27,2f0a230bc6c60d584a8e45456f49e7c560f9bd04,2018-07-03 04:20:24,2018-07-03 04:25:38
1,00008fb52ca81c6767db31f58ea37e7229c372e1,1e80d72011110238e36e73a225c32822660eb028,2018-07-24 21:13:12,2018-07-24 21:18:29
2,000091252c68230bd55a9abda98896c8610994bc,1a62a01395fcf226ea684bc4a61c4a1432ac3cd7,2018-07-08 14:54:20,2018-07-08 15:02:44
3,000091d428154729cbf338d4f51aa95af254d342,1590fe01374b0c4294d5f77e7fae6c9d17492f00,2018-07-09 00:50:27,2018-07-09 01:02:06
4,0000b28d30dd9cf2424e83822b2877fec98b7de5,7ebb433e7b9543abee828108834e8c2a85d878b1,2018-07-28 00:50:02,2018-07-28 00:52:00

In [38]:
# get count info about first session, join 2, 3
user_session_merge = user_session.merge(user_engagement, on='session_id', left_index=True, right_index=True, suffixes=('', '_3'))

In [76]:
# get count info about first session, join 1
data = user_session_merge.merge(user_profile, on='user_id', left_index=True, right_index=True, suffixes=('', '_1'))

In [77]:
data.dtypes

user_id                                       object
session_id                                    object
session_start_timestamp                       object
action_timestamp                              object
Unnamed: 0                                     int64
user_id_3                                     object
session_length                                 int64
view_count                                     int64
view_aoop_overview_count                       int64
view_my_credit_count                           int64
view_credit_monitoring_count                   int64
view_my_recommendations_count                  int64
view_my_borrowing_power_count                  int64
view_cc_best_cards_count                       int64
view_my_debt_count                             int64
view_cc_my_borrowing_power_count               int64
view_cc_approval_odds_count                    int64
view_cc_details_count                          int64
view_my_credit_report_count                    int64
view_increase_total_credit_limit_count         int64
view_cc_marketplace_count                      int64
view_alert_count                               int64
click_count                                    int64
click_count_credit_card                        int64
click_count_personal_loan                      int64
click_count_mortgage                           int64
click_count_credit_repair                      int64
click_count_banking                            int64
click_count_auto_products                      int64
click_apply_count                              int64
                                              ...
tradelines_min_days_since_opened             float64
count_tradelines_closed_accounts               int64
count_total_tradelines_opened_24_months        int64
count_tradelines_cc_opened_24_months           int64
count_tradelines_condition_derogatory          int64
count_open_installment_accounts_24_months      int64
count_tradelines_open_collection_accounts      int64
count_tradelines_open_mortgages                int64
count_tradelines_open_student_loans            int64
count_tradelines_opened_accounts               int64
count_tradelines_open_secured_loans            int64
count_tradelines_open_unsecured_loans          int64
total_tradelines_amount_past_due             float64
total_open_cc_amount_past_due                float64
total_cc_open_balance                        float64
total_tradelines_open_balance                float64
max_cc_limit                                 float64
max_cc_utilization_ratio                     float64
avg_cc_utilization_ratio                     float64
total_mortgage_loans_amount                  float64
total_mortgage_loans_balance                 float64
total_auto_loans_balance                     float64
total_student_loans_balance                  float64
count_inquiries_3_months                       int64
count_inquiries_6_months                       int64
count_inquiries_12_months                      int64
recent_bankruptcy_date                        object
count_bankruptcy                               int64
age_bucket                                    object
credit_score_bucket                           object
Length: 83, dtype: object

In [49]:
data.describe()

,Unnamed: 0,session_length,view_count,view_aoop_overview_count,view_my_credit_count,view_credit_monitoring_count,view_my_recommendations_count,view_my_borrowing_power_count,view_cc_best_cards_count,view_my_debt_count,...,max_cc_utilization_ratio,avg_cc_utilization_ratio,total_mortgage_loans_amount,total_mortgage_loans_balance,total_auto_loans_balance,total_student_loans_balance,count_inquiries_3_months,count_inquiries_6_months,count_inquiries_12_months,count_bankruptcy
count,284565.000000,284565.000000,284565.000000,284565.000000,284565.000000,284565.000000,284565.000000,284565.000000,284565.0,284565.000000,...,131261.000000,131251.000000,2.845650e+05,2.845650e+05,2.845650e+05,284565.000000,284565.000000,284565.000000,284565.000000,284565.000000
mean,142282.000000,323.265257,4.997730,1.157433,0.458718,0.071319,0.395980,0.288595,0.0,0.174087,...,0.707685,0.564170,2.244947e+04,1.916799e+04,6.507858e+03,7775.198408,0.814974,1.413087,2.579007,0.101527
std,82146.984013,2791.356346,5.167276,1.386728,0.926094,0.440391,0.774242,0.641333,0.0,1.062647,...,0.403438,0.384434,8.501122e+04,7.421987e+04,1.314062e+04,25875.829438,1.779768,2.585520,3.931758,0.351966
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,-1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,71141.000000,27.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.400000,0.190000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
50%,142282.000000,162.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.880000,0.610000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,1.000000,1.000000,0.000000
75%,213423.000000,399.000000,7.000000,2.000000,1.000000,0.000000,1.000000,0.000000,0.0,0.000000,...,0.990000,0.920000,0.000000e+00,0.000000e+00,1.001100e+04,0.000000,1.000000,2.000000,3.000000,0.000000
max,284564.000000,929132.000000,164.000000,30.000000,22.000000,19.000000,32.000000,15.000000,0.0,35.000000,...,10.480000,10.480000,7.732500e+06,7.555508e+06,1.777930e+06,827594.000000,53.000000,97.000000,137.000000,10.000000

In [81]:
data.to_csv('merged.csv', index=False)

# Missing value

In [36]:
cs = pd.read_csv('merged.csv')

/Users/jacqueline/miniconda2/envs/py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [37]:
cs.head()

,user_id,session_id,session_start_timestamp,action_timestamp,Unnamed: 0,user_id_3,session_length,view_count,view_aoop_overview_count,view_my_credit_count,...,total_mortgage_loans_balance,total_auto_loans_balance,total_student_loans_balance,count_inquiries_3_months,count_inquiries_6_months,count_inquiries_12_months,recent_bankruptcy_date,count_bankruptcy,age_bucket,credit_score_bucket
0,0000485dbdc19e76bedcaf155b4de9491f414a27,2f0a230bc6c60d584a8e45456f49e7c560f9bd04,2018-07-03 04:20:24,2018-07-03 04:25:38,0,09a33bca3fa1f49f784b9c417e77294737bccab9,187,2,1,0,...,26049.0,0.0,0.0,0,0,0,NaN,0,"(45.0, 50.0]","(630.0, 635.0]"
1,00008fb52ca81c6767db31f58ea37e7229c372e1,1e80d72011110238e36e73a225c32822660eb028,2018-07-24 21:13:12,2018-07-24 21:18:29,1,6f8353af26427d39c9dd3ce84740df54479896dd,359,9,2,1,...,0.0,12992.0,0.0,0,0,1,NaN,0,"(50.0, 55.0]","(575.0, 580.0]"
2,000091252c68230bd55a9abda98896c8610994bc,1a62a01395fcf226ea684bc4a61c4a1432ac3cd7,2018-07-08 14:54:20,2018-07-08 15:02:44,2,60513e969b461d15bc6f91a7a822177b9126c5f4,307,2,1,0,...,86987.0,0.0,0.0,0,0,1,NaN,0,"(50.0, 55.0]","(685.0, 690.0]"
3,000091d428154729cbf338d4f51aa95af254d342,1590fe01374b0c4294d5f77e7fae6c9d17492f00,2018-07-09 00:50:27,2018-07-09 01:02:06,3,531600a9890794688120be32259c356057a2207a,0,1,0,0,...,148912.0,46046.0,0.0,3,3,12,NaN,0,"(50.0, 55.0]","(625.0, 630.0]"
4,0000b28d30dd9cf2424e83822b2877fec98b7de5,7ebb433e7b9543abee828108834e8c2a85d878b1,2018-07-28 00:50:02,2018-07-28 00:52:00,4,d72ab2f9299e7c1db705ab1159825ada25d9dad6,469,8,1,1,...,0.0,16262.0,24134.0,0,0,3,NaN,0,"(20.0, 25.0]","(630.0, 635.0]"

In [38]:
# find columns with large ratio of missing values
check_null = cs.isnull().sum(axis=0).sort_values(ascending=False)/float(len(cs))
check_null[check_null > 0.4]

recent_bankruptcy_date      0.910101
app_version                 0.750535
avg_cc_utilization_ratio    0.538766
max_cc_utilization_ratio    0.538731
dtype: float64

In [39]:
# drop them
cs = cs.dropna(thresh=len(cs)*0.4, axis=1)
cs.shape

(284565, 81)

In [40]:
# find columns with large ratio of missing values
check_null = cs.isnull().sum(axis=0).sort_values(ascending=False)/float(len(cs))
check_null[check_null > 0.4]

avg_cc_utilization_ratio    0.538766
max_cc_utilization_ratio    0.538731
dtype: float64

In [41]:
cs.loc[:, cs.apply(pd.Series.nunique) == 1].columns

Index(['view_cc_best_cards_count', 'view_alert_count'], dtype='object')

In [42]:
# drop that column cuz it's not going to provide any useful information
cs = cs.loc[:, cs.apply(pd.Series.nunique) != 1]
cs.shape

(284565, 79)

In [43]:
# missing string values
objectColumns = cs.select_dtypes(include=['object']).columns
cs[objectColumns].isnull().sum().sort_values(ascending=False)

gender                       34677
city                         24610
state                        12899
browser_name                  7044
age_bucket                    6950
os_name                       1030
session_start_timestamp_3        0
session_id                       0
session_start_timestamp          0
action_timestamp                 0
user_id_3                        0
credit_score_bucket              0
login_platform                   0
user_signup_timestamp            0
state_1                          0
zipcode                          0
user_id                          0
dtype: int64

In [44]:
# drop rows with missing gender, state, age_bucket
cs = cs.loc[cs['gender'].isnull()==False, :]
cs = cs.loc[cs['state'].isnull()==False, :]
cs = cs.loc[cs['age_bucket'].isnull()==False, :]
cs[objectColumns].isnull().sum().sort_values(ascending=False)

city                         10519
browser_name                  5751
os_name                        868
state                            0
session_id                       0
session_start_timestamp          0
action_timestamp                 0
user_id_3                        0
session_start_timestamp_3        0
credit_score_bucket              0
age_bucket                       0
login_platform                   0
user_signup_timestamp            0
state_1                          0
zipcode                          0
gender                           0
user_id                          0
dtype: int64

In [45]:
# missing numerical values 
cs.select_dtypes(include=[np.number]).isnull().sum().sort_values(ascending=False)

avg_cc_utilization_ratio                     122138
max_cc_utilization_ratio                     122130
browser_version                               73357
tradelines_avg_days_since_opened               8363
tradelines_max_days_since_opened               8363
tradelines_min_days_since_opened               8363
click_count_personal_loan.1                       0
click_count_credit_card.1                         0
click_count                                       0
click_count_mortgage.1                            0
click_apply_count                                 0
click_count_auto_products                         0
click_count_banking                               0
click_count_credit_repair                         0
click_count_mortgage                              0
click_count_personal_loan                         0
click_count_credit_card                           0
view_increase_total_credit_limit_count            0
view_cc_marketplace_count                         0
click_count_banking.1                             0
view_my_credit_report_count                       0
view_cc_details_count                             0
view_cc_approval_odds_count                       0
view_cc_my_borrowing_power_count                  0
view_my_debt_count                                0
view_my_borrowing_power_count                     0
view_my_recommendations_count                     0
view_credit_monitoring_count                      0
view_my_credit_count                              0
view_aoop_overview_count                          0
                                              ...
session_length                                    0
click_count_credit_repair.1                       0
count_bankruptcy                                  0
click_count_auto_products.1                       0
count_tradelines_open_unsecured_loans             0
count_inquiries_6_months                          0
count_inquiries_3_months                          0
total_student_loans_balance                       0
total_auto_loans_balance                          0
total_mortgage_loans_balance                      0
total_mortgage_loans_amount                       0
max_cc_limit                                      0
total_tradelines_open_balance                     0
total_cc_open_balance                             0
total_open_cc_amount_past_due                     0
total_tradelines_amount_past_due                  0
count_tradelines_open_secured_loans               0
logged_in_count                                   0
count_tradelines_opened_accounts                  0
count_tradelines_open_student_loans               0
count_tradelines_open_mortgages                   0
count_tradelines_open_collection_accounts         0
count_open_installment_accounts_24_months         0
count_tradelines_condition_derogatory             0
count_tradelines_cc_opened_24_months              0
count_total_tradelines_opened_24_months           0
count_tradelines_closed_accounts                  0
Unnamed: 0_1                                      0
count_inquiries_12_months                         0
Unnamed: 0                                        0
Length: 61, dtype: int64

In [46]:
# Mean interpolation: replace missing values using the mean along the axis.
from sklearn.preprocessing import Imputer
imr = Imputer(missing_values='NaN', strategy='mean', axis=0)

numColumns = cs.select_dtypes(include=[np.number]).columns
imr = imr.fit(cs[numColumns])   # fit data used to calculate the interpolating values
cs[numColumns] = imr.transform(cs[numColumns])  # fill in missing values with interpolating values

# Feature engineering

## Drop meanningless categorical data

In [47]:
objectColumns = cs.select_dtypes(include=['object']).columns
objectColumns

Index(['user_id', 'session_id', 'session_start_timestamp', 'action_timestamp',
       'user_id_3', 'session_start_timestamp_3', 'city', 'state',
       'browser_name', 'login_platform', 'os_name', 'user_signup_timestamp',
       'state_1', 'zipcode', 'gender', 'age_bucket', 'credit_score_bucket'],
      dtype='object')

In [48]:
droplist = ['session_start_timestamp', 'action_timestamp', 'user_signup_timestamp', 'user_id_3', 'session_start_timestamp_3', 'city', 'state_1', 'zipcode', 'browser_name', 'os_name']
cs.drop(droplist, axis=1, inplace=True)

In [49]:
cs.drop(['user_id', 'session_id', 'Unnamed: 0'], axis=1, inplace=True)

In [77]:
cs.drop(['Unnamed: 0_1'], axis=1, inplace=True)

In [50]:
cs.select_dtypes(include=['object']).head()

  state login_platform  gender    age_bucket credit_score_bucket
0    UT     Mobile Web  Female  (45.0, 50.0]      (630.0, 635.0]
2    MN     Mobile Web    Male  (50.0, 55.0]      (685.0, 690.0]
3    IL     Mobile Web  Unisex  (50.0, 55.0]      (625.0, 630.0]
4    TX     Mobile Web  Female  (20.0, 25.0]      (630.0, 635.0]
5    VA     Mobile Web  Female  (35.0, 40.0]      (670.0, 675.0]

## Create Dummy

In [51]:
cs = pd.get_dummies(cs, columns=['state', 'login_platform', 'gender'])

In [52]:
cs.select_dtypes(include=['object']).head()

     age_bucket credit_score_bucket
0  (45.0, 50.0]      (630.0, 635.0]
2  (50.0, 55.0]      (685.0, 690.0]
3  (50.0, 55.0]      (625.0, 630.0]
4  (20.0, 25.0]      (630.0, 635.0]
5  (35.0, 40.0]      (670.0, 675.0]

In [53]:
mapping_dict = {
    'age_bucket': {
    '(15.0, 20.0]': 0,
    '(20.0, 25.0]': 1,
    '(25.0, 30.0]': 2,
    '(30.0, 35.0]': 3,
    '(35.0, 40.0]': 4,
    '(40.0, 45.0]': 5,
    '(45.0, 50.0]': 6,
    '(50.0, 55.0]': 7,
    '(55.0, 60.0]': 8,
    '(60.0, 65.0]': 9,
    '(65.0, 70.0]': 10,
    '(70.0, 75.0]': 11,
    '(75.0, 80.0]': 12,
    '(80.0, 85.0]': 13,
    '(85.0, 90.0]': 14,
    '(90.0, 95.0]': 15,
    '(95.0, 100.0]': 16

},
    'credit_score_bucket': {
    '(495.0, 500.0]': 0,
    '(500.0, 505.0]': 1,
    '(505.0, 510.0]': 2,
    '(510.0, 515.0]': 3,
    '(515.0, 520.0]': 4,
    '(520.0, 525.0]': 5,
    '(525.0, 530.0]': 6,
    '(530.0, 535.0]': 7,
    '(535.0, 540.0]': 8,
    '(540.0, 545.0]': 9,
    '(545.0, 550.0]': 10,
    '(550.0, 555.0]': 11,
    '(555.0, 560.0]': 12,
    '(560.0, 565.0]': 13,
    '(565.0, 570.0]': 14,
    '(570.0, 575.0]': 15,
    '(575.0, 580.0]': 16,
    '(580.0, 585.0]': 17,
    '(585.0, 590.0]': 18,
    '(590.0, 595.0]': 19,
    '(595.0, 600.0]': 20,
    '(600.0, 605.0]': 21,
    '(605.0, 610.0]': 22,
    '(610.0, 615.0]': 23,
    '(615.0, 620.0]': 24,
    '(620.0, 625.0]': 25,
    '(625.0, 630.0]': 26,
    '(630.0, 635.0]': 27,
    '(635.0, 640.0]': 28,
    '(640.0, 645.0]': 29,
    '(645.0, 650.0]': 30,
    '(650.0, 655.0]': 31,
    '(655.0, 660.0]': 32,
    '(660.0, 665.0]': 33,
    '(665.0, 670.0]': 34,
    '(670.0, 675.0]': 35,
    '(675.0, 680.0]': 36,
    '(680.0, 685.0]': 37,
    '(685.0, 690.0]': 38,
    '(690.0, 695.0]': 39,
    '(695.0, 700.0]': 40,
    '(700.0, 705.0]': 41,
    '(705.0, 710.0]': 42,
    '(710.0, 715.0]': 43,
    '(715.0, 720.0]': 44,
    '(720.0, 725.0]': 45,
    '(725.0, 730.0]': 46,
    '(730.0, 735.0]': 47,
    '(735.0, 740.0]': 48,
    '(740.0, 745.0]': 49,
    '(745.0, 750.0]': 50,
    '(750.0, 755.0]': 51,
    '(755.0, 760.0]': 52,
    '(760.0, 765.0]': 53,
    '(765.0, 770.0]': 54,
    '(770.0, 775.0]': 55,
    '(775.0, 780.0]': 56,
    '(780.0, 785.0]': 57,
    '(785.0, 790.0]': 58,
    '(790.0, 795.0]': 59,
    '(795.0, 800.0]': 60
}
}

cs.replace(mapping_dict, inplace=True)

In [54]:
cs['is_homeowner'] = cs['is_homeowner'].astype('uint8')

In [55]:
cs = cs.reset_index(drop=True)
cs.head()

,session_length,view_count,view_aoop_overview_count,view_my_credit_count,view_credit_monitoring_count,view_my_recommendations_count,view_my_borrowing_power_count,view_my_debt_count,view_cc_my_borrowing_power_count,view_cc_approval_odds_count,...,state_WA,state_WI,state_WV,state_WY,login_platform_Mobile App,login_platform_Mobile Web,login_platform_Web,gender_Female,gender_Male,gender_Unisex
0,187.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0
1,307.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,1,0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,1
3,469.0,8.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0
4,291.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0

## numerical

In [56]:
cs.head()

,session_length,view_count,view_aoop_overview_count,view_my_credit_count,view_credit_monitoring_count,view_my_recommendations_count,view_my_borrowing_power_count,view_my_debt_count,view_cc_my_borrowing_power_count,view_cc_approval_odds_count,...,state_WA,state_WI,state_WV,state_WY,login_platform_Mobile App,login_platform_Mobile Web,login_platform_Web,gender_Female,gender_Male,gender_Unisex
0,187.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0
1,307.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,1,0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,1
3,469.0,8.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0
4,291.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,1,0,0

In [57]:
cs.dtypes.unique()

array([dtype('float64'), dtype('uint8'), dtype('int64')], dtype=object)

In [104]:
cs.loc[cs['click_apply_count']>0,'click_apply_count'] = 1

In [106]:
cs['click_apply_count'].value_counts()

0.0    185192
1.0     47946
Name: click_apply_count, dtype: int64

In [107]:
droplist = ['click_apply_count']
y = cs['click_apply_count'].astype('int')
X = cs.drop(droplist, axis=1)
X.shape

(233138, 118)

In [108]:
y.describe()

count    233138.000000
mean          0.205655
std           0.404180
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: click_apply_count, dtype: float64

In [109]:
X.select_dtypes(include=['uint8']).columns.shape

(58,)

In [110]:
col = X.select_dtypes(include=['int64','float64']).columns
col.shape

(60,)

In [111]:
from sklearn.preprocessing import StandardScaler 
sc =StandardScaler() 

X[col] = sc.fit_transform(X[col]) # standardization

In [112]:
X.head()

,session_length,view_count,view_aoop_overview_count,view_my_credit_count,view_credit_monitoring_count,view_my_recommendations_count,view_my_borrowing_power_count,view_my_debt_count,view_cc_my_borrowing_power_count,view_cc_approval_odds_count,...,state_WA,state_WI,state_WV,state_WY,login_platform_Mobile App,login_platform_Mobile Web,login_platform_Web,gender_Female,gender_Male,gender_Unisex
0,-0.046435,-0.581385,-0.117151,-0.496940,-0.162551,-0.513050,-0.449896,-0.164775,-0.126398,-0.13262,...,0,0,0,0,0,1,0,1,0,0
1,-0.005907,-0.581385,-0.117151,-0.496940,-0.162551,-0.513050,-0.449896,-0.164775,-0.126398,-0.13262,...,0,0,0,0,0,1,0,0,1,0
2,-0.109590,-0.774314,-0.836410,-0.496940,-0.162551,-0.513050,-0.449896,-0.164775,-0.126398,-0.13262,...,0,0,0,0,0,1,0,0,0,1
3,0.048805,0.576185,-0.117151,0.579245,-0.162551,0.777619,1.102089,-0.164775,-0.126398,-0.13262,...,0,0,0,0,0,1,0,1,0,0
4,-0.011311,-0.195528,0.602107,-0.496940,-0.162551,-0.513050,-0.449896,-0.164775,-0.126398,-0.13262,...,0,0,0,0,0,1,0,1,0,0

In [113]:
X.describe().T

,count,mean,std,min,25%,50%,75%,max
session_length,233138.0,1.295287e-18,1.000002,-0.109590,-1.004714e-01,-5.521561e-02,0.024489,313.686149
view_count,233138.0,2.072459e-18,1.000002,-0.967242,-5.813852e-01,-3.884568e-01,0.383257,30.673008
view_aoop_overview_count,233138.0,5.985751e-17,1.000002,-0.836410,-8.364095e-01,-1.171512e-01,0.602107,17.864307
view_my_credit_count,233138.0,-1.901786e-17,1.000002,-0.496940,-4.969404e-01,-4.969404e-01,0.579245,23.179146
view_credit_monitoring_count,233138.0,2.660672e-17,1.000002,-0.162551,-1.625515e-01,-1.625515e-01,-0.162551,36.268039
view_my_recommendations_count,233138.0,3.882814e-17,1.000002,-0.513050,-5.130499e-01,-5.130499e-01,0.777619,40.788347
view_my_borrowing_power_count,233138.0,-6.278333e-18,1.000002,-0.449896,-4.498956e-01,-4.498956e-01,-0.449896,22.829869
view_my_debt_count,233138.0,-6.095469e-18,1.000002,-0.164775,-1.647748e-01,-1.647748e-01,-0.164775,29.809835
view_cc_my_borrowing_power_count,233138.0,-4.144919e-18,1.000002,-0.126398,-1.263975e-01,-1.263975e-01,-0.126398,59.816776
view_cc_approval_odds_count,233138.0,-2.663720e-17,1.000002,-0.132620,-1.326205e-01,-1.326205e-01,-0.132620,33.089661
view_cc_details_count,233138.0,2.767343e-17,1.000002,-0.213429,-2.134294e-01,-2.134294e-01,-0.213429,68.077525
view_my_credit_report_count,233138.0,2.218751e-17,1.000002,-0.210445,-2.104454e-01,-2.104454e-01,-0.210445,36.492626
view_increase_total_credit_limit_count,233138.0,2.224846e-17,1.000002,-0.136827,-1.368272e-01,-1.368272e-01,-0.136827,63.102298
view_cc_marketplace_count,233138.0,3.363175e-17,1.000002,-0.126776,-1.267757e-01,-1.267757e-01,-0.126776,87.707519
click_count,233138.0,8.814048e-17,1.000002,-0.700076,-5.995972e-01,-3.986404e-01,0.204230,32.658759
click_count_credit_card,233138.0,3.352508e-17,1.000002,-0.233490,-2.334897e-01,-2.334897e-01,-0.233490,54.983582
click_count_personal_loan,233138.0,-7.619336e-19,1.000002,-0.143540,-1.435397e-01,-1.435397e-01,-0.143540,89.063576
click_count_mortgage,233138.0,1.712827e-17,1.000002,-0.055894,-5.589411e-02,-5.589411e-02,-0.055894,57.160535
click_count_credit_repair,233138.0,7.558382e-18,1.000002,-0.104554,-1.045543e-01,-1.045543e-01,-0.104554,43.644614
click_count_banking,233138.0,-1.310526e-18,1.000002,-0.020786,-2.078593e-02,-2.078593e-02,-0.020786,184.588382
click_count_auto_products,233138.0,-3.535372e-18,1.000002,-0.022027,-2.202685e-02,-2.202685e-02,-0.022027,125.997523
click_count_credit_card.1,233138.0,1.804259e-17,1.000002,-0.349564,-3.495641e-01,-3.495641e-01,-0.349564,48.820140
click_count_personal_loan.1,233138.0,1.636633e-17,1.000002,-0.148861,-1.488612e-01,-1.488612e-01,-0.148861,49.148286
click_count_mortgage.1,233138.0,-1.228237e-17,1.000002,-0.108722,-1.087224e-01,-1.087224e-01,-0.108722,135.702494
click_count_credit_repair.1,233138.0,1.444626e-17,1.000002,-0.082493,-8.249348e-02,-8.249348e-02,-0.082493,105.396655
click_count_banking.1,233138.0,-1.889595e-18,1.000002,-0.017400,-1.739957e-02,-1.739957e-02,-0.017400,144.857624
click_count_auto_products.1,233138.0,2.938016e-17,1.000002,-0.044750,-4.474969e-02,-4.474969e-02,-0.044750,113.975506
logged_in_count,233138.0,-5.059239e-17,1.000002,-1.649370,2.667883e-01,2.667883e-01,0.266788,36.673798
browser_version,233138.0,1.859118e-18,1.000002,-1.414776,-2.062692e-16,-2.062692e-16,0.524415,226.869805
is_homeowner,233138.0,2.682274e-01,0.443038,0.000000,0.000000e+00,0.000000e+00,1.000000,1.000000
...,...,...,...,...,...,...,...,...
state_NC,233138.0,4.508917e-02,0.207500,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_ND,233138.0,1.166691e-03,0.034137,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_NE,233138.0,5.082826e-03,0.071113,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_NH,233138.0,2.706551e-03,0.051954,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_NJ,233138.0,2.398150e-02,0.152992,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_NM,233138.0,3.830349e-03,0.061771,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_NV,233138.0,1.001553e-02,0.099575,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_NY,233138.0,4.721238e-02,0.212093,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_OH,233138.0,3.393269e-02,0.181056,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_OK,233138.0,1.106641e-02,0.104614,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_OR,233138.0,7.729328e-03,0.087576,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_PA,233138.0,4.225394e-02,0.201168,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_RI,233138.0,2.860966e-03,0.053412,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_SC,233138.0,1.691702e-02,0.128961,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_SD,233138.0,7.763642e-04,0.027853,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_TN,233138.0,2.944608e-02,0.169054,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_TX,233138.0,1.081548e-01,0.310577,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_UT,233138.0,6.112260e-03,0.077942,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_VA,233138.0,2.442330e-02,0.154360,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_VT,233138.0,1.059458e-03,0.032532,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_WA,233138.0,1.764191e-02,0.131646,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_WI,233138.0,1.034151e-02,0.101166,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_WV,233138.0,3.753142e-03,0.061148,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
state_WY,233138.0,1.222452e-03,0.034942,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
login_platform_Mobile App,233138.0,2.816615e-01,0.449810,0.000000,0.000000e+00,0.000000e+00,1.000000,1.000000
login_platform_Mobile Web,233138.0,6.049121e-01,0.488871,0.000000,0.000000e+00,1.000000e+00,1.000000,1.000000
login_platform_Web,233138.0,1.134264e-01,0.317114,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000
gender_Female,233138.0,4.756668e-01,0.499409,0.000000,0.000000e+00,0.000000e+00,1.000000,1.000000
gender_Male,233138.0,3.261673e-01,0.468810,0.000000,0.000000e+00,0.000000e+00,1.000000,1.000000
gender_Unisex,233138.0,1.981659e-01,0.398619,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000

In [114]:
X.shape

(233138, 118)

In [120]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

rfe = RFE(model, 30) # keep only 30 features
rfe = rfe.fit(X[:20000], y[:20000])
print(rfe.support_)
print(rfe.ranking_) # 1s are features selected

[False  True False  True False False  True False False False False False
 False False  True False False False False False False  True  True  True
  True False  True False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True False  True False False False False False False  True
 False False  True  True  True False  True  True False False False False
 False  True False False False False False False  True False  True  True
 False  True False False False False False  True  True  True False False
  True False False False  True  True  True False False False]
[88  1 12  1 75  7  1 78 53 50 76 36 48 61  1 42 24 49 77 86 57  1  1  1  1
  9  1 14  1 28 22 21 23 43 33 35 45 16 44 72 15 63 85 64 80 71 29 83 56 31
 59 38 89 70 84 55 66 67 60 32 34 51  1 27  1 73 18 20 19 52  6  1 39 54  1
  1  1 47  1  1 46  8 81 40 13  1 11 17  5 79 30 74  1 41  1  1 25  1 37 26
 82 62 87  1  1  1 69 65  1 10 58 68  1  1  1  3  2  4]

In [121]:
col_filter_1 = X.columns[rfe.support_]
col_filter_1

Index(['view_count', 'view_my_credit_count', 'view_my_borrowing_power_count',
       'click_count', 'click_count_credit_card.1',
       'click_count_personal_loan.1', 'click_count_mortgage.1',
       'click_count_credit_repair.1', 'click_count_auto_products.1',
       'browser_version', 'state_AL', 'state_AZ', 'state_GA', 'state_ID',
       'state_IL', 'state_IN', 'state_KY', 'state_LA', 'state_MO', 'state_NJ',
       'state_NV', 'state_NY', 'state_OK', 'state_TN', 'state_TX', 'state_UT',
       'state_WA', 'login_platform_Mobile App', 'login_platform_Mobile Web',
       'login_platform_Web'],
      dtype='object')

In [122]:
corrMatrix = X[col_filter_1].corr()
upTri = np.triu(corrMatrix.as_matrix(), 1) # triu() returns the upper trangular part of the matrix
absUptri = np.abs(upTri)
corrMatrix = pd.DataFrame(absUptri, columns=corrMatrix.columns)
colList = corrMatrix.apply(lambda x: all(x <= 0.55))
col_filter_2 = col_filter_1[colList]

In [126]:
col_filter_2.values

array(['view_count', 'click_count_credit_card.1',
       'click_count_personal_loan.1', 'click_count_mortgage.1',
       'click_count_credit_repair.1', 'click_count_auto_products.1',
       'browser_version', 'state_AL', 'state_AZ', 'state_GA', 'state_ID',
       'state_IL', 'state_IN', 'state_KY', 'state_LA', 'state_MO',
       'state_NJ', 'state_NV', 'state_NY', 'state_OK', 'state_TN',
       'state_TX', 'state_UT', 'state_WA', 'login_platform_Mobile App',
       'login_platform_Web'], dtype=object)

In [124]:
col_filter_2.shape

(26,)

In [134]:
col_used = ['click_apply_count', 'gender_Female', 'gender_Male', 'gender_Unisex', 'age_bucket', 'credit_score_bucket'] + list(col_filter_2.values)
col_used

['click_apply_count',
 'gender_Female',
 'gender_Male',
 'gender_Unisex',
 'age_bucket',
 'credit_score_bucket',
 'view_count',
 'click_count_credit_card.1',
 'click_count_personal_loan.1',
 'click_count_mortgage.1',
 'click_count_credit_repair.1',
 'click_count_auto_products.1',
 'browser_version',
 'state_AL',
 'state_AZ',
 'state_GA',
 'state_ID',
 'state_IL',
 'state_IN',
 'state_KY',
 'state_LA',
 'state_MO',
 'state_NJ',
 'state_NV',
 'state_NY',
 'state_OK',
 'state_TN',
 'state_TX',
 'state_UT',
 'state_WA',
 'login_platform_Mobile App',
 'login_platform_Web']

In [135]:
cs[col_used].to_csv('regression.csv', index=False)

## Train Model

In [91]:
X_input = X[col_filter_2] # using filter approach
y_input = y[col_filter_2]

n_sample = y.shape[0]
n_pos_sample = y[y==0].shape[0]
n_neg_sample = y[y==1].shape[0]
print(n_pos_sample, n_neg_sample)

print('total samples: {}; positive: {:.2%}; negative: {:.2%}'.format(n_sample, n_pos_sample / n_sample, n_neg_sample / n_sample))
print('feature dimension: ', X.shape[1])

185192 31013
total samples: 233138; positive: 79.43%; negative: 13.30%
feature dimension:  118

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0) 

# param grid search ï¼Œcv=5-fold
clf = LogisticRegression()
clf2.fit(X[:20000], y[:20000])

# takes about 30 min to finish